import React from 'react';
import Navigation from './routes/Navigation';
import firestore from '@react-native-firebase/firestore';

export default function App() {
  // firestore().collection('DDL').doc('TUD-541').set({
  //   BTTR_No: 4,
  //   TDLS_No: 7,
  //   Trip_No: 9,
  //   LoginCategoryID: 1,
  //   LoginId: 'sample string 5',
  //   Delivery_Status: 1,
  //   Delivery_StatusDec: 'sample string 6',
  //   TractorNo: 1,
  //   TractorNumberPlate: 'sample string 7',
  //   DriverNo: 1,
  //   DriverName: 'sample string 8',
  //   DecanterNo: 1,
  //   DecanterName: 'sample string 9',
  //   ScheduledStart: '2021-09-04T18:45:01.5320356+05:00',
  //   ScheduledDate: 'sample string 10',
  //   ScheduledFinish: '2021-09-04T18:45:01.5320356+05:00',
  //   TerminalStarting: 1,
  //   TerminalStartingName: 'sample string 11',
  //   TerminalEnding: 1,
  //   TerminalEndingName: 'sample string 12',
  //   PrimaryProduct: 'sample string 13',
  //   ProductName: 'sample string 14',
  //   CustomerNo: 'sample string 15',
  //   CustomerName: 'sample string 16',
  //   TankerCode: 'sample string 17',
  //   TankerShortName: 'sample string 18',
  //   ScheduledAmount: 1,
  //   CreditLimit: 1.1,
  //   AvailableAmount: 1.1,
  //   ETA: '2021-09-04T18:45:01.5320356+05:00',
  //   isDeliveryCharges: true,
  //   Trip_Status: 5,
  //   Trip_StatusDec: 'Submitted',
  //   Type: 1,
  //   StatusReason: 'sample string 20',
  //   odometerin: 1.1,
  //   odometerout: 1.1,
  //   timein: '2021-09-04T18:45:01.5320356+05:00',
  //   timeout: '2021-09-04T18:45:01.5320356+05:00',
  //   datein: '2021-09-04T18:45:01.5320356+05:00',
  //   dateout: '2021-09-04T18:45:01.5320356+05:00',
  //   vehicleno: 'sample string 21',
  //   weighbridgeno: 'sample string 22',
  //   vie_press_start: 1.1,
  //   vie_level_start: 1.1,
  //   tanker_press_start: 1.1,
  //   tanker_level_start: 1.1,
  //   tanker_content_start: 1.1,
  //   tanker_weight_start: 1.1,
  //   tanker_flowmeter_start: 1.1,
  //   vie_press_end: 1.1,
  //   vie_level_end: 1.1,
  //   tanker_press_end: 1.1,
  //   tanker_level_end: 1.1,
  //   tanker_content_end: 1.1,
  //   tanker_weight_end: 1.1,
  //   tanker_flowmeter_end: 1.1,
  //   tanker_press_diff: 1.1,
  //   tanker_level_diff: 1.1,
  //   tanker_content_diff: 1.1,
  //   tanker_weight_diff: 1.1,
  //   tanker_flowmeter_diff: 1.1,
  //   vie_press_start_unit: 'sample string 23',
  //   vie_level_start_unit: 'sample string 24',
  //   tanker_press_start_unit: 'sample string 25',
  //   tanker_level_start_unit: 'sample string 26',
  //   vie_press_end_unit: 'sample string 27',
  //   vie_level_end_unit: 'sample string 28',
  //   tanker_press_end_unit: 'sample string 29',
  //   tanker_level_end_unit: 'sample string 30',
  //   uom: 'sample string 31',
  //   Tdls_Status: 1,
  //   Tdls_StatusDec: 'sample string 32',
  //   latitude_in: 'sample string 33',
  //   longitude_in: 'sample string 34',
  //   latitude_out: 'sample string 35',
  //   longitude_out: 'sample string 36',
  //   spervisor_name: 'sample string 37',
  //   driver_name: 'sample string 38',
  //   decanter_name: 'sample string 39',
  //   remarks: 'sample string 40',
  //   DeliveryNote: 'sample string 41',
  //   PurchaseOrder: 'sample string 42',
  //   SupplyDate: '2021-09-04T18:45:01.5320356+05:00',
  //   Plant: 'sample string 43',
  //   ManualTDLSNo: 1,
  //   isManualTDLSNo: true,
  //   CalculationBaseTypeID: 1,
  //   CalculationBaseType: 'sample string 44',
  //   CalculationContentTypeID: 1,
  //   CalculationContentType: 'sample string 45',
  //   Image: 'sample string 46',
  //   ImagePath: 'sample string 47',
  //   Signature: 'sample string 48',
  //   SignaturePath: 'sample string 49',
  //   TDLSRemarks: [],
  //   content_start_unit: 'sample string 50',
  //   content_end_unit: 'sample string 51',
  //   Additional_Remarks: 'sample string 52',
  //   Trip_Reason: 'sample string 53',
  //   Weighbridge_No: 'sample string 54',
  //   NetWeight: 55,
  // });
  return <Navigation />;
}
